# Exception handling

print("Exception handling")

try:
    a = [2, 3]
    print(a[3])
except Exception as e:
    print(e)
